# Generated by Django 5.2.14 on 2026-05-14 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offered_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('advance_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of invoice amount', max_digits=5)),
                ('discount_rate', models.DecimalField(decimal_places=2, help_text='Annual discount rate %', max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('financier_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_disbursement', models.DecimalField(decimal_places=2, help_text='offered_amount - platform_fee - financier_fee', max_digits=15)),
                ('repayment_amount', models.DecimalField(decimal_places=2, help_text='Amount buyer/supplier repays to financier', max_digits=15)),
                ('tenor_days', models.IntegerField(default=30, help_text='Finance tenor in days')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('settled', 'Settled')], default='submitted', max_length=20)),
                ('terms', models.TextField(blank=True, help_text='Additional terms and conditions')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financing_offers', to='organisations.organisation')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='invoices.invoice')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
