# Generated by Django 5.2.14 on 2026-05-14 16:27

import apps.invoices.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('purchase_order_number', models.CharField(blank=True, max_length=100)),
                ('grn_number', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZWG', 'Zimbabwe Gold'), ('ZAR', 'South African Rand'), ('GBP', 'British Pound'), ('EUR', 'Euro')], default='USD', max_length=5)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_buyer_approval', 'Pending Buyer Approval'), ('clarification_requested', 'Clarification Requested'), ('approved_by_buyer', 'Approved by Buyer'), ('available_for_financing', 'Available for Financing'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('settlement_pending', 'Settlement Pending'), ('settled', 'Settled'), ('repayment_pending', 'Repayment Pending'), ('repaid', 'Repaid'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('risk_rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unrated', 'Unrated')], default='unrated', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_invoices', to='organisations.organisation')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_invoices', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('supplier', 'buyer', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('po', 'Purchase Order'), ('grn', 'Goods Received Note'), ('delivery_note', 'Delivery Note'), ('other', 'Other')], default='invoice', max_length=20)),
                ('file', models.FileField(upload_to=apps.invoices.models.invoice_document_path)),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='invoices.invoice')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='invoices.invoice')),
            ],
            options={
                'verbose_name_plural': 'Invoice status histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
